### ISSUE TITLE
Any plans for a local version?

### ISSUE THREAD

**Issue by smashah** [amajai/whatsapp-link-text#1]
Cool project, is there any reason why the data needs to be extracted via a server instead of locally? Are you planning to release the code for https://whatsapp-link-text-server.herokuapp.com?

Thanks

**Comment by amajai** [comment]
Thanks, I appreciate the kind comment. I originally wanted to create a script within the React app where it fetches the URL of an article site, parse the data needed and post them to the html page. However, every time I try to fetch a URL, I get an error mentioning that the access to fetch URL has been blocked by CORS. 

From my understanding, this is because the CORS header on the remote server is not configured to permit direct access from the browser. You can read more about it [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) and [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Browsers in general restrict cross-origin HTTP requests. 

So I had to create a server-side in form of an API where CORS is allowed and can easily run a script with no issue. I actually released the code but it is in a different repo [here](https://github.com/amajai/whatsapp-link-text-server). Hope that answers your question.

**Comment by smashah** [comment]
Ah of course. Thanks for sharing the link to the repo.
